[2024-11-15T13:13:26.294+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_dag.preprocess_data scheduled__2024-11-14T00:00:00+00:00 [queued]>
[2024-11-15T13:13:26.327+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_dag.preprocess_data scheduled__2024-11-14T00:00:00+00:00 [queued]>
[2024-11-15T13:13:26.328+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-11-15T13:13:26.354+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): preprocess_data> on 2024-11-14 00:00:00+00:00
[2024-11-15T13:13:26.374+0000] {standard_task_runner.py:60} INFO - Started process 433 to run task
[2024-11-15T13:13:26.381+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_dag', 'preprocess_data', 'scheduled__2024-11-14T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/random.py', '--cfg-path', '/tmp/tmp0uuc4w0d']
[2024-11-15T13:13:26.383+0000] {standard_task_runner.py:88} INFO - Job 25: Subtask preprocess_data
[2024-11-15T13:13:26.557+0000] {task_command.py:423} INFO - Running <TaskInstance: ml_pipeline_dag.preprocess_data scheduled__2024-11-14T00:00:00+00:00 [running]> on host 8b834e0277f8
[2024-11-15T13:13:26.620+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='suvarna' AIRFLOW_CTX_DAG_ID='ml_pipeline_dag' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-14T00:00:00+00:00'
[2024-11-15T13:13:26.622+0000] {random.py:46} ERROR - Error in preprocessing data: 'NoneType' object has no attribute 'drop'
[2024-11-15T13:13:26.622+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/random.py", line 47, in preprocess_data
    raise e  # Re-raise the error to ensure task failure
  File "/opt/airflow/dags/random.py", line 31, in preprocess_data
    X = global_df.drop('target', axis=1)
AttributeError: 'NoneType' object has no attribute 'drop'
[2024-11-15T13:13:26.629+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=ml_pipeline_dag, task_id=preprocess_data, execution_date=20241114T000000, start_date=20241115T131326, end_date=20241115T131326
[2024-11-15T13:13:26.638+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 25 for task preprocess_data ('NoneType' object has no attribute 'drop'; 433)
[2024-11-15T13:13:26.652+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-15T13:13:26.691+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
