[2024-11-15T15:22:16.460+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: ml_pipeline_dag.load_and_preprocess_data manual__2024-11-15T15:17:11.618626+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
